# Project information
site_name: å¤é›¶ç­”ç–‘
site_url: https://gu0.io
site_author: GU0
site_description: >-
  Write your documentation in Markdown and create a professional static site in
  minutes â€“ searchable, customizable, in 60+ languages, for all devices

# Repository
#repo_name: gu0qa/qa
#repo_url: https://github.com/gu0qa/qa

# Copyright
copyright: Copyright &copy; 2024 å¤é›¶ç­”ç–‘

extra_javascript:
  - 'https://code.jquery.com/jquery-3.5.1.slim.min.js'
  - 'https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js'
  - 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js'

extra_css:
  # - 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css'
  - 'css/custom.css'  # å¯é€‰é¡¹ï¼Œç”¨äºæ·»åŠ è‡ªå®šä¹‰CSS

# Configuration
theme:
  name: material
  #custom_dir: theme
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  language: 'zh'
  highlightjs: true
  hljs_languages:
    - yaml
    - django
  favicon: 'assets/favicon.ico'
  # logo: 'assets/logo.png'

plugins:
  - search
  - glightbox
  
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

not_in_nav: |
  /tutorials/**/*.md


# Page tree
nav:
  - ç­”ç–‘æ–‡ç« : 
    - answering-question/index.md
    - 2024å¹´ç­”ç–‘: 
      - 6æœˆ25æ—¥: 
        - answering-question/2024/0625/index.md
    - 2023å¹´ç­”ç–‘: 
      - 1æœˆ8æ—¥: qa/index.md
    - 2022å¹´ç­”ç–‘: 
      - 11æœˆ4æ—¥: qa/index.md
  
  - æ„è¯†å¼ºåº¦æå‡ç‚¹å®æ“æŒ‡å—:
    - practical-guide-to-enhancing-consciousness-intensity/index.md
    - ã€1ã€‘ä¸­å¤®åŒºï¼šå¿ƒæ™ºæ§åˆ¶åŒº: practical-guide-to-enhancing-consciousness-intensity/01/index.md
    - ã€2ã€‘ä¸Šæ–¹åŒºï¼šè‡ªä¸»æ„è¯†åŒº: practical-guide-to-enhancing-consciousness-intensity/02/index.md
    - ã€3ã€‘ä¸‹æ–¹åŒºï¼šç¥æ€§è¿æ¥åŒº: practical-guide-to-enhancing-consciousness-intensity/03/index.md
    - ã€4ã€‘å³æ–¹åŒºï¼šæ€ç»´æ‰©å±•åŒº: practical-guide-to-enhancing-consciousness-intensity/04/index.md
    - ã€5ã€‘å·¦æ–¹åŒºï¼šæ—§æœ‰æƒ¯æ€§åŒº: practical-guide-to-enhancing-consciousness-intensity/05/index.md
    - ã€6ã€‘å·¦ä¸ŠåŒºï¼šç¥ç»è”ç»œåŒº: practical-guide-to-enhancing-consciousness-intensity/06/index.md
    - ã€7ã€‘å·¦ä¸‹åŒºï¼šç¥æ€§äº¤æ¢åŒº: practical-guide-to-enhancing-consciousness-intensity/07/index.md
    - ã€8ã€‘å³ä¸ŠåŒºï¼šçµæ€§ç»“æ„åŒº: practical-guide-to-enhancing-consciousness-intensity/08/index.md
    - ã€9ã€‘å³ä¸‹åŒºï¼šæ¨¡å—äº¤æ¢åŒº: practical-guide-to-enhancing-consciousness-intensity/09/index.md
  - çŸ©é˜µè„±ç¦»æŒ‡å—:
    - æ„è¯†å¼ºåº¦: 
        - matrix-detachment-guide/index.md
    - ç›—æ¢¦ç©å®¶: 
        - matrix-detachment-guide/index.md
    - æ²‰å¯‚å°æˆ‘: 
        - matrix-detachment-guide/index.md
    - åŒ–è§£æ”»å‡»:
        - matrix-detachment-guide/index.md
    - å¤é›¶è„±æ•: 
        - matrix-detachment-guide/index.md

  - æ½œæ„è¯†å‚¬çœ åŸ¹è®­:
    - subconscious-hypnosis-training/index.md
    - åˆçº§ç­ ğŸ‘½ :
      - ç¬¬ 8 æœŸ: 
        - subconscious-hypnosis-training/index.md
      - ç¬¬ 7 æœŸ: 
        - subconscious-hypnosis-training/index.md
      - ç¬¬ 6 æœŸ:
        - subconscious-hypnosis-training/index.md
      - ç¬¬ 5 æœŸ:
        - subconscious-hypnosis-training/index.md
      - ç¬¬ 4 æœŸ:
        - subconscious-hypnosis-training/index.md
      - ç¬¬ 3 æœŸ:
        - subconscious-hypnosis-training/index.md
      - ç¬¬ 2 æœŸ:
        - subconscious-hypnosis-training/index.md
      - ç¬¬ 1 æœŸ:
        - subconscious-hypnosis-training/index.md
    - ä¸­çº§ç­ ğŸ‘½ :
      - ç¬¬ 2 æœŸ: 
        - subconscious-hypnosis-training/index.md
      - ç¬¬ 1 æœŸ: 
        - subconscious-hypnosis-training/index.md
    - é«˜çº§ç­ ğŸ‘½ :
      - ç¬¬ 1 æœŸ: 
        - subconscious-hypnosis-training/index.md
  - å­¦å‘˜æŠ•ç¨¿:
    - student-submissions/index.md
    - 2024å¹´: 
        - student-submissions/2024/index.md
    - 2023å¹´:
        - student-submissions/2023/index.md
        - "âˆã€å¤é›¶æ½œå‚¬ã€‘ä¼˜ç§€æ½œå‚¬æ¡ˆä¾‹-ä¸å®‰å…¨æ„Ÿçš„è„±æ•ç ´å¹»ï¼ˆé™„å¤é›¶ç‚¹è¯„ï¼‰": ./student-submissions/2023/0720/index.md
        - "âˆ å¤é›¶æ½œæ„è¯†å‚¬çœ -å¤–çµå¹²æ‰°2": ./student-submissions/2023/0710/index.md
        - "âˆã€å¤é›¶æ½œå‚¬ã€‘ä¸­çº§ç­ & å­¦å‘˜æš—å‚¬æ¡ˆä¾‹ï¼ˆé™„å¤é›¶ç‚¹è¯„ï¼‰": ./student-submissions/2023/0705/index.md
        - "âˆã€å¤é›¶æ½œå‚¬ã€‘å­¦å‘˜æŠ•ç¨¿-å¦‚ä½•å›¢ç»“èµ·æ¥é›†ä½“è§‰é†’ï¼›é›†ä½“å¤§é‡‘è›‹ä¸ä¸ªäººå¤§é‡‘è›‹å¦‚ä½•äº’åŠ¨ï¼ˆé™„å¤é›¶ç‚¹è¯„ï¼‰": ./student-submissions/2023/0609/index.md
        - "âˆã€å¤é›¶æ½œå‚¬ã€‘å­¦å‘˜äº’å‚¬ä¿¡æ¯-æ½œå‚¬é›†ä½“é˜²å¾¡ç³»ç»Ÿç»™å¤§å®¶çš„è¯ï¼ˆé™„å¤é›¶ç‚¹è¯„ï¼‰": ./student-submissions/2023/0608/index.md
        - "âˆã€å¤é›¶æ½œå‚¬ã€‘å­¦å‘˜æŠ•ç¨¿ï¼šè¿‘ç™¾åœºäº’å‚¬é˜¶æ®µæ€§æ€»ç»“ï¼ˆé™„å¤é›¶ç‚¹è¯„ï¼‰": ./student-submissions/2023/0511/index.md
        - "âˆã€å¤é›¶æ½œå‚¬ã€‘å­¦å‘˜æŠ•ç¨¿ï¼šç ´é»‘å±â€”â€”è§å®‡å®™": ./student-submissions/2023/0504/index.md

  - ç”µå½±æ¨è:
    - movie-recommendations/index.md
    - 1ã€è¡¨æ„è¯†å’Œæ½œæ„è¯†å…³ç³»çš„æ¢ç´¢:
      - â–ªï¸ å…¥ä¾µè„‘ç»†èƒ (The Cell): movie-recommendations/01/001.md
    - 2ã€ç²¾åˆ†çš„æ¢ç´¢:
      - â–ªï¸ è‡´å‘½ID (Identity):  movie-recommendations/02/001.md
      - â–ªï¸ æ— åŒ (Project Gutenberg): movie-recommendations/02/002.md
      - â–ªï¸ æš´é£é›¨:  movie-recommendations/02/003.md
    - 3ã€æ½œæ„è¯†åŠå¤åˆä½“èƒ½çš„æ¢ç´¢: 
      - â–ªï¸ è¶…æ„ŸçŒæ€: movie-recommendations/03/001.md
    - 4ã€è§‰é†’æ„è¯†çš„æ¢ç´¢: 
      - â–ªï¸ æ¥šé—¨çš„ä¸–ç•Œ: movie-recommendations/04/001.md
      - â–ªï¸ è‚–ç”³å…‹çš„æ•‘èµ: movie-recommendations/04/002.md
      - â–ªï¸ æ°¸æ— æ­¢å¢ƒ: movie-recommendations/04/003.md
      - â–ªï¸ å¤±æ§ç©å®¶: movie-recommendations/04/004.md
      - â–ªï¸ ç‘å…‹å’Œè«è’‚: movie-recommendations/04/005.md
    - 5ã€è½®å›ç³»ç»Ÿå’Œå‚¬çœ æ¤å…¥çš„æ¢ç´¢: 
      - â–ªï¸ å‘½è¿è§„åˆ’å±€: movie-recommendations/05/001.md
      - â–ªï¸ ç¾æ¢¦æˆçœŸ: movie-recommendations/05/002.md
      - â–ªï¸ çˆ±ä¸ç½ª: movie-recommendations/05/003.md
      - â–ªï¸ ä»²å¤å¤œæƒŠé­‚: movie-recommendations/05/004.md
      - â–ªï¸ å“ªå’: movie-recommendations/05/005.md
      - â–ªï¸ å¤©æ‰æªæ‰‹: movie-recommendations/05/006.md
      - â–ªï¸ é»‘å®¢å¸å›½: movie-recommendations/05/007.md
      - â–ªï¸ è¥¿éƒ¨ä¸–ç•Œ: movie-recommendations/05/008.md
      - â–ªï¸ ç§»é­‚éƒ½å¸‚: movie-recommendations/05/009.md
      - â–ªï¸ å¼‚æ¬¡å…ƒéª‡å®¢: movie-recommendations/05/010.md
      - â–ªï¸ åˆ†æ­§è€…: movie-recommendations/05/011.md
      - â–ªï¸ äº‘å›¾: movie-recommendations/05/012.md
      - â–ªï¸ å¿ƒçµå¥‡æ—…: movie-recommendations/05/013.md
    - 6ã€ç»´åº¦æ—¶é—´çº¿å’Œæ½œæ„è¯†æ¢ç´¢: 
      - â–ªï¸ å˜ç„¦: movie-recommendations/06/001.md
      - â–ªï¸ é»‘é•œç¬¬å…­å­£: movie-recommendations/06/1-002.md
      - â–ªï¸ æ— å§“ä¹‹äºº: movie-recommendations/06/1-003.md
      - â–ªï¸ è¾¹ç¼˜ä¸–ç•Œ: movie-recommendations/06/1-004.md
    - 7ã€æ‰§å¿µçš„æ¢ç´¢: 
      - â–ªï¸ éæˆ‘: movie-recommendations/07/001.md
      - â–ªï¸ ç‹©çŒ: movie-recommendations/07/002.md
      - â–ªï¸ ææ€–æ¸¸è½®: movie-recommendations/07/003.md
    - 8ã€å‡ºç¥æ¢ç´¢: 
      - â–ªï¸ çµå¼‚ç©ºé—´: movie-recommendations/08/001.md
      - â–ªï¸ æ„è¯†å¼ºæ®–: movie-recommendations/08/002.md
      - â–ªï¸ å¹½å†¥: movie-recommendations/08/003.md
      - â–ªï¸ éå…¥è™šæ— : movie-recommendations/08/004.md
    - 9ã€æ¸…é†’æ¢¦çš„æ¢ç´¢: 
      - â–ªï¸ å¼‚ç•Œ: movie-recommendations/09/001.md
      - â–ªï¸ è®°å¿†æå–: movie-recommendations/09/002.md
      - â–ªï¸ å¹»æ¢¦ç©ºé—´: movie-recommendations/09/003.md
      - â–ªï¸ çº¢è¾£æ¤’: movie-recommendations/09/004.md
      - â–ªï¸ ç›—æ¢¦ç©ºé—´: movie-recommendations/09/005.md
      - â–ªï¸ æ¢¦é­‡ä¹‹æ—…: movie-recommendations/09/006.md
      - â–ªï¸ è¶…çº§çš„æˆ‘: movie-recommendations/09/007.md
    - 10ã€è§‚ç”µå½±æ³•çš„æ¢ç´¢: 
      - â–ªï¸ ä¹°å‡¶æ‹äºº: movie-recommendations/10/001.md
      - â–ªï¸ ç‰¹æ®Šæ¼”å‘˜: movie-recommendations/10/002.md
      - â–ªï¸ å¥½è±åä¿—å¥—å¤§åæ§½: movie-recommendations/10/003.md
    - 11ã€ç ´ææƒ§å¹»çš„æ¢ç´¢: 
      - â–ªï¸ æƒŠå£°å°–ç¬‘: movie-recommendations/11/001.md
      - â–ªï¸ æ‘„å½±æœºä¸è¦åœ: movie-recommendations/11/002.md
      - â–ªï¸ æ—ä¸­å°å±‹: movie-recommendations/11/003.md
    - 12ã€åˆä¸€æœ¬æºçš„æ¢ç´¢: 
      - â–ªï¸ è¶…ä½“: movie-recommendations/12/001.md
      - â–ªï¸ ç¬æ¯å…¨å®‡å®™: movie-recommendations/12/002.md
      - â–ªï¸ å®‡å®™ä¹‹æ—…: movie-recommendations/12/003.md
      - â–ªï¸ è½®å›: movie-recommendations/12/004.md
      - â–ªï¸ å¤©åœ°ç„é»„: movie-recommendations/12/005.md
    - 13ã€è‡ªå¼ºè‡ªçˆ±çš„æ¢ç´¢: 
      - â–ªï¸ æ­»äº¡è¯—ç¤¾: movie-recommendations/12/001.md
      - â–ªï¸ è·³å‡ºæˆ‘å¤©åœ°: movie-recommendations/12/002.md
      - â–ªï¸ å¿ƒçµæ•æ‰‹: movie-recommendations/12/003.md
      - â–ªï¸ å¥”è…¾å¹´ä»£: movie-recommendations/12/004.md
      - â–ªï¸ å½“å¹¸ç¦æ¥æ•²é—¨: movie-recommendations/12/005.md
      - â–ªï¸ åšå¼ºStonger: movie-recommendations/12/006.md
    - 14ã€åPUAçš„æ¢ç´¢: 
      - â–ªï¸ é›·æ©è²å°”å¾·: movie-recommendations/12/001.md
